import { withVectorIcon } from 'phantom-library';
import BroadcastIconInline from './broadcast.svg';
import BroadcastSVG from './broadcast.svg?react';
import CircleFillSVG from './circle_fill.svg?react';
import CircleSVG from './circle.svg?react';
import DottedLineSVG from './dotted_line.svg?react';
import FacebookSVG from './facebook.svg?react';
import FullscreenExitSVG from './fullscreen_exit.svg?react';
import FullscreenSVG from './fullscreen.svg?react';
import LocalMemoryIconSVG from './local_memory_icon.svg?react';
import LocalMemorySVG from './local_memory.svg?react';
import LocationPinFillInline from './location_pin_fill.svg';
import LocationPinSVG from './location_pin.svg?react';
import NewsIconInline from './news.svg';
import NewsSVG from './news.svg?react';
import RadioIconInline from './radio.svg';
import RadioSVG from './radio.svg?react';
import SquareSVG from './square_fill.svg?react';
import SwipeSVG from './swipe.svg?react';
import TouchSVG from './touch.svg?react';
import TVIconInline from './tv.svg';
import TVSVG from './tv.svg?react';
import TwitterSVG from './twitter.svg?react';
import YouTubeSVG from './youtube.svg?react';

export const LocalMemoryFullIcon = withVectorIcon(LocalMemorySVG);
export const LocalMemoryIcon = withVectorIcon(LocalMemoryIconSVG);
export const LocationPinIcon = withVectorIcon(LocationPinSVG);
export { LocationPinFillInline };
export const FacebookIcon = withVectorIcon(FacebookSVG);
export const TwitterIcon = withVectorIcon(TwitterSVG);
export const YouTubeIcon = withVectorIcon(YouTubeSVG);
export const NewsIcon = withVectorIcon(NewsSVG);
export const TVIcon = withVectorIcon(TVSVG);
export const BroadcastIcon = withVectorIcon(BroadcastSVG);
export const RadioIcon = withVectorIcon(RadioSVG);
export { NewsIconInline, TVIconInline, BroadcastIconInline, RadioIconInline };
export const CircleIcon = withVectorIcon(CircleSVG);
export const CircleFillIcon = withVectorIcon(CircleFillSVG);
export const DottedLineIcon = withVectorIcon(DottedLineSVG);
export const SquareFillIcon = withVectorIcon(SquareSVG);

export const FullscreenIcon = withVectorIcon(FullscreenSVG);
export const FullscreenExitIcon = withVectorIcon(FullscreenExitSVG);
export const SwipeIcon = withVectorIcon(SwipeSVG);
export const TouchIcon = withVectorIcon(TouchSVG);
